name: Deploy to PythonAnywhere

on:
  push:
    branches:
      - main  # 當 main 分支更新時觸發

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: 檢出代碼
      - name: Checkout repository
        uses: actions/checkout@v3


      # Step 2: 發送 Webhook 請求
      - name: Notify PythonAnywhere via Webhook
        run: |
          curl -X POST \
          -H "X-Webhook-Secret: ${{ secrets.TOKEN }}" \
          https://WorkSpace01.pythonanywhere.com/webhook          