name: Deploy to PythonAnywhere

on:
  push:
    branches:
      - main  # 當 main 分支更新時觸發

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: 檢出代碼
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: 通知 PythonAnywhere 更新代碼並重啟
      - name: Deploy to PythonAnywhere
        run: |
          curl -X POST \
          -H "Authorization: Token ${{ secrets.TOKEN }}" \
          https://www.pythonanywhere.com/api/v0/user/WorkSpace01/webapps/WorkSpace01.pythonanywhere.com/reload/