name: Deploy to PythonAnywhere

on:
  push:
    branches:
      - main  # 當推送到 main 分支時觸發部署

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9  # PythonAnywhere 支援的版本

        
      # 呼叫 PythonAnywhere 控制台來執行 git pull 命令
      - name: Upload project to PythonAnywhere
        env:
          USERNAME: ${{ secrets.USERNAME }}  # PythonAnywhere 使用者名稱
          TOKEN: ${{ secrets.TOKEN }}  # PythonAnywhere API token
          DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}  # 專案的絕對路徑，如 /order-testuse
        run: |
          curl -X POST -H "Authorization: Token $TOKEN" \ 
          -d "command=cd $DEPLOY_PATH && git pull origin main" \
          "https://www.pythonanywhere.com/api/v0/user/$USERNAME/consoles/"

      # 在虛擬環境中安裝依賴
      - name: Install dependencies on PythonAnywhere
        env:
          USERNAME: ${{ secrets.USERNAME }}
          TOKEN: ${{ secrets.TOKEN }}
          DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
        run: |
          curl -X POST -H "Authorization: Token $TOKEN" \
          -d "command=cd $DEPLOY_PATH && source flask-venv/bin/activate && pip install --upgrade pip && pip install -r requirements.txt" \
          "https://www.pythonanywhere.com/api/v0/user/$USERNAME/consoles/"

      # 重啟 Web 應用以使更改生效
      - name: Reload PythonAnywhere Web App
        env:
          USERNAME: ${{ secrets.USERNAME }}
          TOKEN: ${{ secrets.TOKEN }}
        run: |
          curl -X POST -H "Authorization: Token $TOKEN" \
          "https://www.pythonanywhere.com/api/v0/user/$USERNAME/webapps/WorkSpace01/reload/"